export const INGREDIENTS = [
    // Beverages
    'apple cider',
    'apple juice',
    'club soda',
    'hot chocolate',
    'coffee',
    'cola',
    'diet cola',
    'eggnog',
    'fruit punch',
    'ginger ale',
    'instant coffee',
    'lemon lime soda',
    'lemonade',
    'orange juice',
    'pineapple juice',
    'tomato juice',

    // Bread
    'bagels',
    'bread',
    'bread dough',
    'buns',
    'corn bread',
    'breadcrumbs',
    'egg roll wraps',
    'english muffins',
    'flat bread',
    'french bread',
    'hoagie rolls',
    'ice cream cones',
    'italian bread',
    'pie crust',
    'pita bread',
    'pizza crust',
    'rolls',
    'rye bread',
    'tortillas',
    'wheat bread',
    'white bread',
    'wonton wrappers',

    // Canned Products
    'baked beans',
    'beans',
    'beef broth',
    'beef soup',
    'black beans',
    'canned corn',
    'canned tomatoes',
    'cheese soup',
    'chicken broth',
    'chili',
    'corned beef hash',
    'crab bisque',
    'cream of celery soup',
    'cream of chicken soup',
    'cream of corn soup',
    'cream of mushroom soup',
    'cream of onion soup',
    'cream of shrimp soup',
    'cream of vegetable soup',
    'french onion soup',
    'garbanzo beans',
    'gumbo',
    'kidney beans',
    'lima beans',
    'minestrone',
    'pork and beans',
    'refried beans',
    'tomato paste',
    'tomato soup',
    'vegetable stock',

    // Cereal
    'cereal',
    'cheerios',
    'cinnamon crunch cereal',
    'crunch cereal',
    'flakes cereal',
    'hex cereal',
    'rice krispies',

    // Condiments
    'applesauce',
    'barbecue sauce',
    'dijon mustard',
    'hot sauce',
    'burgundy wine',
    'caramel',
    'caesar dressing',
    'cheese sauce',
    'chili sauce',
    'chocolate syrup',
    'cocktail sauce',
    'corn syrup',
    'cranberry sauce',
    'curry sauce',
    'white wine',
    'french dressing',
    'garlic sauce',
    'grape jelly',
    'gravy',
    'guacamole',
    'honey',
    'honey mustard',
    'horseradish',
    'italian dressing',
    'jam',
    'ketchup',
    'marsala wine',
    'mayonnaise',
    'miracle whip',
    'molasses',
    'mustard',
    'nutella',
    'orange jelly',
    'oyster sauce',
    'peanut butter',
    'pesto',
    'poppy seed dressing',
    'ranch dressing',
    'red wine',
    'relish',
    'salsa',
    'sandwich spread',
    'sherry wine',
    'soy sauce',
    'meat sauce',
    'steak sauce',
    'maple syrup',
    'taco sauce',
    'teriyaki sauce',
    'thousand island dressing',
    'tabasco sauce',
    'tomato sauce',
    'vermouth',
    'vinaigrette',
    'vinegar',
    'balsamic vinegar',
    'cider vinegar',
    'red vinegar',
    'red wine vinegar',
    'white vinegar',
    'whipped cream',
    'white sauce',
    'worcestershire sauce',

    // Dairy
    'american cheese',
    'blue cheese',
    'blue cheese crumbles',
    'butter',
    'buttermilk',
    'cheddar cheese',
    'cheese',
    'chocolate milk',
    'coconut milk',
    'colby cheese',
    'evaporated milk',
    'condensed milk',
    'whipped cream',
    'cottage cheese',
    'cream',
    'cream cheese',
    'eggs',
    'feta cheese',
    'goat cheese',
    'half and half',
    'heavy cream',
    'ice cream',
    'jack cheese',
    'milk',
    'monterey jack',
    'mozzarella cheese',
    'parmesan cheese',
    'provolone cheese',
    'ricotta cheese',
    'romano cheese',
    'sour cream',
    'swiss cheese',
    'velveeta',
    'yogurt',

    // Ingredients
    'allspice',
    'almond extract',
    'angel food cake mix',
    'apple pie filling',
    'baking chocolate',
    'baking powder',
    'baking soda',
    'barbecue seasoning',
    'basil',
    'bay leaves',
    'black pepper',
    'bread mix',
    'brown sugar',
    'cajun seasoning',
    'canola oil',
    'cayenne pepper',
    'celery salt',
    'chili powder',
    'chili seasoning',
    'chives',
    'chocolate chips',
    'chocolate pudding mix',
    'cilantro',
    'cinnamon',
    'cloves',
    'coconut extract',
    'cooking spray',
    'corn bread mix',
    'cornmeal',
    'corn oil',
    'cornstarch',
    'creole seasoning',
    'cumin',
    'curry powder',
    'dark cake mix',
    'dill',
    'dry mustard',
    'fennel seed',
    'flour',
    'whole wheat flour',
    'garlic powder',
    'garlic salt',
    'ginger',
    'italian seasoning',
    'lemon herb seasoning',
    'lemon extract',
    'lemon juice',
    'lemon pepper',
    'light cake mix',
    'lime juice',
    'meat seasoning',
    'mint leaves',
    'nutmeg',
    'olive oil',
    'onion powder',
    'onion soup mix',
    'oregano',
    'pancake mix',
    'paprika',
    'parsley',
    'peanut oil',
    'peppercorns',
    'poppy seeds',
    'powdered sugar',
    'pumpkin pie filling',
    'pumpkin pie spice',
    'ranch seasoning mix',
    'red pepper flakes',
    'rosemary',
    'salt',
    'seasoning salt',
    'sesame oil',
    'sesame seeds',
    'shortening',
    'spice cake mix',
    'splenda',
    'sugar',
    'taco seasoning',
    'thyme',
    'turkey drippings',
    'vanilla extract',
    'vanilla pudding mix',
    'vegetable oil',
    'white pepper',
    'yeast',
    'yellow cake mix',

    // Liquor
    'baileys',
    'beer',
    'brandy',
    'coconut rum',
    'gin',
    'grand marnier',
    'kahlua',
    'pale ale',
    'raspberry liqueur',
    'rum',
    'stout',
    'tequila',
    'triple sec',
    'vodka',
    'whiskey',

    // Meats
    'bacon',
    'beef',
    'bologna',
    'brisket',
    'canned chicken',
    'chicken',
    'chicken breast',
    'cocktail sausages',
    'corned beef',
    'ground beef',
    'ground meat',
    'ground pork',
    'ground turkey',
    'ground veal',
    'ham',
    'hot dog',
    'kielbasa',
    'lamb',
    'meatballs',
    'pepperoni',
    'polish sausage',
    'pork chops',
    'pork roast',
    'pork tenderloin',
    'prosciutto',
    'pot roast',
    'salami',
    'sausage',
    'sliced chicken',
    'sliced ham',
    'sliced roast beef',
    'sliced turkey',
    'steak',
    'turkey breast',
    'turkey legs',

    // Pasta / Grains
    'angel hair pasta',
    'barley',
    'black rice',
    'bowtie pasta',
    'brown rice',
    'egg noodles',
    'elbow macaroni',
    'fettuccine',
    'gnocchi',
    'granola',
    'lasagna noodles',
    'mac and cheese',
    'oats',
    'orzo',
    'pasta',
    'ramen',
    'rice',
    'rigatoni',
    'rotini',
    'shell pasta',
    'spaghetti',
    'tortellini',
    'white rice',
    'wild rice',
    'ravioli',

    // Produce
    'apples',
    'artichokes',
    'asparagus',
    'avocado',
    'banana',
    'green beans',
    'black olives',
    'blueberries',
    'broccoli',
    'brussels sprouts',
    'butternut squash',
    'cabbage',
    'carrot',
    'cauliflower',
    'celery',
    'cherries',
    'cherry tomatoes',
    'chilis',
    'coconut',
    'corn',
    'cranberries',
    'cucumber',
    'eggplant',
    'fruit',
    'garlic',
    'grapefruit',
    'grapes',
    'snap beans',
    'green chilis',
    'green olives',
    'green onions',
    'green peppers',
    'jalapenos',
    'lemons',
    'lettuce',
    'limes',
    'mango',
    'mushrooms',
    'olives',
    'onions',
    'oranges',
    'peaches',
    'pears',
    'peas',
    'peppers',
    'pickles',
    'pineapple',
    'potatoes',
    'mashed potatoes',
    'red potatoes',
    'sweet potatoes',
    'pumpkin',
    'raisins',
    'raspberries',
    'red peppers',
    'sauerkraut',
    'scallions',
    'spinach',
    'squash',
    'strawberries',
    'tomatoes',
    'turnip',
    'vegetables',
    'watermelon',
    'yellow peppers',
    'zucchini',
    'kale',

    // Seafood
    'canned tuna',
    'catfish',
    'clams',
    'cod',
    'crab',
    'fish',
    'haddock',
    'salmon',
    'scallops',
    'shrimp',
    'swordfish',
    'tilapia',
    'tuna',

    // Snacks
    'almonds',
    'cashews',
    'cheese crackers',
    'chocolate bars',
    'crackers',
    'doritos',
    'frozen fries',
    'frozen hash browns',
    'frozen tater tots',
    'graham crackers',
    'jello',
    'kit kat',
    'm&ms',
    'marshmallows',
    'nuts',
    'oreos',
    'oyster crackers',
    'peanuts',
    'pecans',
    'popcorn',
    'potato chips',
    'pretzels',
    'ritz crackers',
    'saltines',
    'tortilla chips',
    'walnuts',
    'wheat thins',
    'twinkie',
] as const;
